from .compat import compat26Str as compat26Str
from _typeshed import Incomplete

izip = zip

class ChaCha:
    constants: Incomplete
    @staticmethod
    def rotl32(v, c): ...
    @staticmethod
    def quarter_round(x, a, b, c, d) -> None: ...
    @classmethod
    def double_round(cls, x) -> None: ...
    @staticmethod
    def chacha_block(key, counter, nonce, rounds): ...
    @staticmethod
    def word_to_bytearray(state): ...
    key: Incomplete
    nonce: Incomplete
    counter: Incomplete
    rounds: Incomplete
    def __init__(self, key, nonce, counter: int = 0, rounds: int = 20) -> None: ...
    def encrypt(self, plaintext): ...
    def decrypt(self, ciphertext): ...
