from _typeshed import Incomplete

def compat26Str(x): ...
def compatHMAC(x): ...
def compatAscii2Bytes(val): ...
def compat_b2a(val): ...
def raw_input(s): ...
def a2b_hex(s): ...
def a2b_base64(s): ...
def b2a_hex(b): ...
def b2a_base64(b): ...
def readStdinBinary(): ...
def compatLong(num): ...

int_types: Incomplete

def formatExceptionTrace(e): ...
def time_stamp(): ...
def remove_whitespace(text): ...

bytes_to_int: Incomplete

def bit_length(val): ...
def int_to_bytes(val, length: Incomplete | None = None, byteorder: str = "big"): ...
def byte_length(val): ...

ecdsaAllCurves: bool
ML_KEM_AVAILABLE: bool
