def parseDateClass(s): ...
def createDateClass(year, month, day, hour, minute, second): ...
def printDateClass(d): ...
def getNow(): ...
def getHoursFromNow(hours): ...
def getMinutesFromNow(minutes): ...
def isDateClassExpired(d): ...
def isDateClassBefore(d1, d2): ...
