def deprecated_class_name(
    old_name,
    warn: str = "Class name '{old_name}' is deprecated, please use '{new_name}'",
): ...
def deprecated_params(
    names, warn: str = "Param name '{old_name}' is deprecated, please use '{new_name}'"
): ...
def deprecated_instance_attrs(
    names, warn: str = "Attribute '{old_name}' is deprecated, please use '{new_name}'"
): ...
def deprecated_attrs(
    names, warn: str = "Attribute '{old_name}' is deprecated, please use '{new_name}'"
): ...
def deprecated_method(message): ...
