class DSAKey:
    def __init__(self, p, q, g, x, y) -> None: ...
    def __len__(self) -> int: ...
    def hasPrivateKey(self) -> None: ...
    def hashAndSign(self, data, hAlg) -> None: ...
    def sign(self, data) -> None: ...
    def hashAndVerify(self, signature, data, hAlg: str = "sha1") -> None: ...
    @staticmethod
    def generate(L, N) -> None: ...
    @staticmethod
    def generate_qp(L, N) -> None: ...
