from .cryptomath import *
from .tripledes import *

def new(key, mode, IV): ...

class OpenSSL_TripleDES(TripleDES):
    def __init__(self, key, mode, IV) -> None: ...
    def encrypt(self, plaintext): ...
    def decrypt(self, ciphertext): ...
    def __del__(self) -> None: ...
