from .cryptomath import *
from .rc4 import RC4 as RC4
from _typeshed import Incomplete

def new(key): ...

class OpenSSL_RC4(RC4):
    rc4: Incomplete
    def __init__(self, key) -> None: ...
    def __del__(self) -> None: ...
    def encrypt(self, plaintext): ...
    def decrypt(self, ciphertext): ...
