from .cryptomath import *
from .rc4 import *
from _typeshed import Incomplete

def new(key): ...

class PyCrypto_RC4(RC4):
    context: Incomplete
    def __init__(self, key) -> None: ...
    def encrypt(self, plaintext): ...
    def decrypt(self, ciphertext): ...
