from _typeshed import Incomplete

class AsyncStateMachine:
    result: Incomplete
    handshaker: Incomplete
    closer: Incomplete
    reader: Incomplete
    writer: Incomplete
    def __init__(self) -> None: ...
    def wantsReadEvent(self): ...
    def wantsWriteEvent(self): ...
    def outConnectEvent(self) -> None: ...
    def outCloseEvent(self) -> None: ...
    def outReadEvent(self, readBuffer) -> None: ...
    def outWriteEvent(self) -> None: ...
    def inReadEvent(self) -> None: ...
    def inWriteEvent(self) -> None: ...
    def setHandshakeOp(self, handshaker) -> None: ...
    def setServerHandshakeOp(self, **args) -> None: ...
    def setCloseOp(self) -> None: ...
    def setWriteOp(self, writeBuffer) -> None: ...
