from .asyncstatemachine import AsyncStateMachine as AsyncStateMachine
from _typeshed import Incomplete
from tlslite.tlsconnection import TLSConnection as TLSConnection

class TLSAsyncDispatcherMixIn(AsyncStateMachine):
    tlsConnection: Incomplete
    siblingClass: Incomplete
    def __init__(self, sock: Incomplete | None = None) -> None: ...
    def readable(self): ...
    def writable(self): ...
    def handle_read(self) -> None: ...
    def handle_write(self) -> None: ...
    def outConnectEvent(self) -> None: ...
    def outCloseEvent(self) -> None: ...
    readBuffer: Incomplete
    def outReadEvent(self, readBuffer) -> None: ...
    def outWriteEvent(self) -> None: ...
    def recv(self, bufferSize: int = 16384): ...
    def send(self, writeBuffer): ...
    def close(self) -> None: ...
