from tlslite.tlsconnection import TLSConnection as TLSConnection

class TLSSocketServerMixIn:
    def finish_request(self, sock, client_address) -> None: ...
    def handshake(self, tlsConnection) -> None: ...
