from _typeshed import Incomplete

class BaseDB:
    type: Incomplete
    filename: Incomplete
    db: Incomplete
    lock: Incomplete
    def __init__(self, filename, type) -> None: ...
    def create(self) -> None: ...
    def open(self) -> None: ...
    def __getitem__(self, username): ...
    def __setitem__(self, username, value) -> None: ...
    def __delitem__(self, username) -> None: ...
    def __contains__(self, username) -> bool: ...
    def check(self, username, param): ...
    def keys(self): ...
