from _typeshed import Incomplete

class BufferedSocket:
    socket: Incomplete
    buffer_writes: bool
    def __init__(self, socket) -> None: ...
    def send(self, data): ...
    def sendall(self, data): ...
    def flush(self) -> None: ...
    def recv(self, bufsize): ...
    def getsockname(self): ...
    def getpeername(self): ...
    def settimeout(self, value): ...
    def gettimeout(self): ...
    def setsockopt(self, level, optname, value): ...
    def shutdown(self, how): ...
    def close(self): ...
