from .utils.asn1parser import ASN1Parser as ASN1Parser
from .utils.cryptomath import bytesToNumber as bytesToNumber
from .utils.pem import dePem as dePem

def parseBinary(data): ...
def parse(data): ...
