from .utils.compat import compat26Str as compat26Str, compatHMAC as compatHMAC
from .utils.cryptomath import MD5 as MD5, SHA1 as SHA1
from _typeshed import Incomplete

class HandshakeHashes:
    def __init__(self) -> None: ...
    def update(self, data) -> None: ...
    def digest(self, digest: Incomplete | None = None): ...
    def digestSSL(self, masterSecret, label): ...
    def copy(self): ...
