from .utils.tackwrapper import *
from .utils.pem import *
from .utils import cryptomath as cryptomath
from .x509 import X509 as X509
from _typeshed import Incomplete

class X509CertChain:
    x509List: Incomplete
    def __init__(self, x509List: Incomplete | None = None) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def parsePemList(self, s) -> None: ...
    def getNumCerts(self): ...
    def getEndEntityPublicKey(self): ...
    def getFingerprint(self): ...
    def checkTack(self, tack): ...
    def getTackExt(self): ...
