from .utils.cryptomath import *
from .utils.pem import *
from .constants import AlgorithmOID as AlgorithmOID, RSA_PSS_OID as RSA_PSS_OID
from .utils.asn1parser import ASN1Parser as ASN1Parser
from .utils.compat import b2a_hex as b2a_hex, compatHMAC as compatHMAC
from _typeshed import Incomplete

class X509:
    bytes: Incomplete
    serial_number: Incomplete
    subject_public_key: Incomplete
    publicKey: Incomplete
    subject: Incomplete
    certAlg: Incomplete
    sigalg: Incomplete
    issuer: Incomplete
    def __init__(self) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def parse(self, s): ...
    def parseBinary(self, cert_bytes) -> None: ...
    def getFingerprint(self): ...
    def writeBytes(self): ...
