from . import biginteger as biginteger
from ..constants import Attribute as Attribute

def decode_dsa_domain_parameters(der): ...
def encode_dsa_domain_parameters(obj): ...
def encode_dsa_public_key(key): ...
def decode_dsa_public_key(der): ...
def encode_dsa_signature(signature): ...
def decode_dsa_signature(der): ...
