from ..constants import Attribute as Attribute, ObjectClass as ObjectClass
from ..mechanisms import KeyType as KeyType

def encode_named_curve_parameters(oid): ...
def decode_ec_public_key(der, encode_ec_point: bool = True): ...
def decode_ec_private_key(der): ...
def encode_ec_public_key(key): ...
def encode_ecdsa_signature(signature): ...
def decode_ecdsa_signature(der): ...
