from ..common.utils import struct_parse as struct_parse
from ..construct import CString as CString
from .constants import SH_FLAGS as SH_FLAGS
from .notes import iter_notes as iter_notes
from _typeshed import Incomplete

class Segment:
    header: Incomplete
    stream: Incomplete
    def __init__(self, header, stream) -> None: ...
    def data(self): ...
    def __getitem__(self, name): ...
    def section_in_segment(self, section): ...

class InterpSegment(Segment):
    def __init__(self, header, stream) -> None: ...
    def get_interp_name(self): ...

class NoteSegment(Segment):
    elffile: Incomplete
    def __init__(self, header, stream, elffile) -> None: ...
    def iter_notes(self): ...
